# Generated by Django 5.0.2 on 2025-09-03 11:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="文档标题")),
                (
                    "file",
                    models.FileField(upload_to="documents/", verbose_name="文档文件"),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("docx", "Word"),
                            ("md", "Markdown"),
                            ("txt", "Text"),
                        ],
                        max_length=10,
                        verbose_name="文档类型",
                    ),
                ),
                ("file_size", models.BigIntegerField(verbose_name="文件大小(字节)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "上传中"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="uploading",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "extracted_text",
                    models.TextField(blank=True, verbose_name="提取的文本"),
                ),
                ("summary", models.TextField(blank=True, verbose_name="文档摘要")),
                ("keywords", models.JSONField(default=list, verbose_name="关键词")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="上传时间"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="处理完成时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "文档",
                "verbose_name_plural": "文档",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chunk_type",
                    models.CharField(
                        choices=[
                            ("paragraph", "段落"),
                            ("dialogue", "对话"),
                            ("example", "示例"),
                            ("instruction", "说明"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="分块类型",
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                ("order", models.IntegerField(default=0, verbose_name="顺序")),
                ("metadata", models.JSONField(default=dict, verbose_name="元数据")),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="document_processor.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "文档分块",
                "verbose_name_plural": "文档分块",
                "ordering": ["document", "order"],
            },
        ),
        migrations.CreateModel(
            name="LearningPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="包名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("conversation", "对话示例"),
                            ("knowledge", "知识库"),
                            ("training", "训练材料"),
                            ("reference", "参考资料"),
                        ],
                        max_length=20,
                        verbose_name="包类型",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "total_chunks",
                    models.IntegerField(default=0, verbose_name="总分块数"),
                ),
                (
                    "total_examples",
                    models.IntegerField(default=0, verbose_name="总示例数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "documents",
                    models.ManyToManyField(
                        related_name="learning_packages",
                        to="document_processor.document",
                        verbose_name="包含文档",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_packages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "学习包",
                "verbose_name_plural": "学习包",
                "ordering": ["-updated_at"],
            },
        ),
    ]
