# Generated by Django 4.2.7 on 2025-09-03 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="会话ID"
                    ),
                ),
                (
                    "ai_name",
                    models.CharField(
                        default="Mira", max_length=50, verbose_name="AI名称"
                    ),
                ),
                (
                    "ai_avatar",
                    models.URLField(
                        default="/images/ai-avatar.png", verbose_name="AI头像"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否活跃"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "last_interaction",
                    models.DateTimeField(auto_now=True, verbose_name="最后交互时间"),
                ),
                (
                    "ai_personality",
                    models.JSONField(default=dict, verbose_name="AI个性设置"),
                ),
                (
                    "conversation_style",
                    models.CharField(
                        choices=[
                            ("friendly", "友好"),
                            ("professional", "专业"),
                            ("casual", "随意"),
                            ("romantic", "浪漫"),
                        ],
                        default="friendly",
                        max_length=20,
                        verbose_name="对话风格",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI对话会话",
                "verbose_name_plural": "AI对话会话",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AIMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "文字"),
                            ("audio", "语音"),
                            ("image", "图片"),
                            ("video", "视频"),
                            ("system", "系统消息"),
                        ],
                        max_length=20,
                        verbose_name="消息类型",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[("user", "用户"), ("ai", "AI"), ("system", "系统")],
                        max_length=20,
                        verbose_name="发送者",
                    ),
                ),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "content_url",
                    models.URLField(blank=True, null=True, verbose_name="媒体内容URL"),
                ),
                ("metadata", models.JSONField(default=dict, verbose_name="消息元数据")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="是否已读"),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="是否已处理"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_engine.aiconversation",
                        verbose_name="对话会话",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI对话消息",
                "verbose_name_plural": "AI对话消息",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AIPersonality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="个性名称"
                    ),
                ),
                ("description", models.TextField(verbose_name="个性描述")),
                (
                    "personality_traits",
                    models.JSONField(default=dict, verbose_name="个性特征"),
                ),
                (
                    "speaking_style",
                    models.JSONField(default=dict, verbose_name="说话风格"),
                ),
                ("interests", models.JSONField(default=list, verbose_name="兴趣爱好")),
                ("system_prompt", models.TextField(verbose_name="系统提示词")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "AI个性配置",
                "verbose_name_plural": "AI个性配置",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AIResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response_content", models.TextField(verbose_name="回复内容")),
                (
                    "response_type",
                    models.CharField(
                        choices=[
                            ("text", "文字"),
                            ("audio", "语音"),
                            ("image", "图片"),
                            ("video", "视频"),
                            ("system", "系统消息"),
                        ],
                        max_length=20,
                        verbose_name="回复类型",
                    ),
                ),
                (
                    "response_url",
                    models.URLField(blank=True, null=True, verbose_name="回复媒体URL"),
                ),
                (
                    "confidence_score",
                    models.FloatField(default=0.8, verbose_name="置信度"),
                ),
                (
                    "response_time",
                    models.FloatField(default=0.0, verbose_name="响应时间(秒)"),
                ),
                (
                    "model_used",
                    models.CharField(
                        default="virtual", max_length=100, verbose_name="使用的模型"
                    ),
                ),
                (
                    "generation_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        max_digits=10,
                        verbose_name="生成成本",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="生成时间"),
                ),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_engine.aimessage",
                        verbose_name="原始消息",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI回复",
                "verbose_name_plural": "AI回复",
                "ordering": ["-created_at"],
            },
        ),
    ]
