# Generated by Django 5.0.2 on 2025-09-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_system", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
